CREATE TABLE IF NOT EXISTS Users(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Title VARCHAR(255) ,
    Adress VARCHAR(255) ,
    UserID INT ,
    FOREIGN KEY (UserId) REFERENCES Users(ID) ,
    PRIMARY KEY (ID)
)
